spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:incidents_db}
    username: ${POSTGRES_USER:incidents_user}
    password: ${POSTGRES_PASSWORD:incidents_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s
    cache-names: incidents, incidentById, statsByStatus, statsByPrioridade, commentsByIncident

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:default-insecure-secret-key}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.incidents: DEBUG
    org.springframework.security: INFO
