spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incidents_db
    username: incidents_user
    password: incidents_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jwt:
    secret: # secret key
    expiration: 86400000 # 24 hours
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
server:
  port: 8080
